server:
  port: 7777
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quant?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: quant_user
    password: roskfl11!
    driver-class-name: com.mysql.cj.jdbc.Driver
  codec:
    max-in-memory-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false

krx:
  base-url: https://data-dbg.krx.co.kr/svc/apis/sto
  auth-key: "7EED7AEFACC24B34A00F0167EA7516FA0169AFB4"
  timeout-seconds: 30
  response-charset: MS949

logging:
  level:
    top.tradesystem: DEBUG
    org.mybatis: DEBUG
